# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG   = nano
BOARD_SUB   = atmega328
ARDUINO_DIR = /Applications/Arduino.app/Contents/Java
MONITOR_PORT  = /dev/cu.usbserial-14410
AVRDUDE_ARD_BAUDRATE = 115200
MONITOR_BAUDRATE = 9600
ARDUINO_LIBS = SoftwareSerial SPI Wire EEPROM AdafruitSensor AdafruitBUSIO AdafruitBME AdafruitBMP AdafruitMPL AdafruitINA SensorDHT OneWire
# ARDUINO_SKETCHBOOK = /Users/adamfrank/Documents/JagSat2021/jsfc_2021/libraries

include /usr/local/Cellar/arduino-mk/1.6.0/Arduino.mk
