# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG   = nano
BOARD_SUB   = atmega328
ARDUINO_DIR = /Applications/Arduino.app/Contents/Java
MONITOR_PORT  = /dev/cu.usbserial-14210
AVRDUDE_ARD_BAUDRATE = 57600
MONITOR_BAUDRATE = 9600
# ARDUINO_LIBS = SoftwareSerial

include /usr/local/Cellar/arduino-mk/1.6.0/Arduino.mk
